spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    password: postgres
    username: postgres
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

excel-management:
  skip-lines:
    action-history: 5
    actual-avg-sales: 7
  header-row-index:
    action-history: 4
    actual-avg-sales: 6
  file-path:
    action-history: C:\Users\Yaroslav Yarmoshyk\IdeaProjects\data\cyclic-action\action.xlsx
    actual-avg-sales: C:\Users\Yaroslav Yarmoshyk\IdeaProjects\data\cyclic-action\avg.xlsx
  output-directory:
    action-history: C:\Users\Yaroslav Yarmoshyk\IdeaProjects\etake-batch\cyclic-action-batch\src\main\resources\

cyclic-action:
  start-date: 2023-05-17
  end-date: 2023-05-30