spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    password: postgres
    username: postgres
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

excel-management:
  skip-lines:
    action-history: 5
    actual-avg-sales: 6
  header-row-index:
    action-history: 4
    actual-avg-sales: 5
  file-path:
    action-history: C:\Users\Ya.Yarmoshyk\Desktop\Звіти на java\Прогнозування акцій\дані\Акційна історія.xlsx
    actual-avg-sales: C:\Users\Ya.Yarmoshyk\Desktop\Звіти на java\Прогнозування акцій\дані\Актуальні СДП.xlsx
  output-directory:
    action-history: C:\Users\Ya.Yarmoshyk\Desktop\Звіти на java\Прогнозування акцій\

cyclic-action:
  start-date: 2023-05-03
  end-date: 2023-05-16